version: "3.8"

services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    # volumes:
    #   - chromadb_data:/chroma/.chroma/index
    # environment:
    #   - IS_PERSISTENT=TRUE

# volumes:
#   chromadb_data:
